name: Fullstack CI

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/${{ github.repository }}/backend
  IMAGE_FRONTEND: ghcr.io/${{ github.repository }}/frontend
  TARGET_PATH: /root/app

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: npm test # Command to execute your project's tests

      - name: Login to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ---------- BACKEND ----------
      - name: Build Backend
        run: |
          docker build -t $IMAGE_BACKEND:latest ./backend

      - name: Push Backend
        run: docker push $IMAGE_BACKEND:latest

      # ---------- FRONTEND ----------
      - name: Build Frontend
        run: |
          docker build -t $IMAGE_FRONTEND:latest ./frontend

      - name: Push Frontend
        run: docker push $IMAGE_FRONTEND:latest
  deploy:
    runs-on: ubuntu-latest
    needs: test-build-and-push

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # - name: Login to Registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run docker compose up on remote server
        uses: appleboy/ssh-action@v1.0.3 # Use a marketplace action for SSH
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/
            docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml down 
            docker-compose -f docker-compose.yml up -d
            docker image prune -f # Clean up old images

      # - name: Remote and Deploy to VPS
      #   run: |
      #     ssh -o StrictHostKeyChecking=no \
      #     -i ~/.ssh/key \
      #     ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
      #       cd /home
      #       docker-compose pull
      #       docker-compose down
      #       docker-compose up -d
      #     EOF
